services:

  postgres:
    image: postgres:15-alpine
    container_name: evalbee-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - evalbee-net

  backend:
    build: .
    container_name: evalbee-backend
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - evalbee-net


volumes:
  postgres_data:

networks:
  evalbee-net:
    external: true